### PR TITLE
Fix autocomplete

### PR DESCRIPTION
**Pull request by thiagola92**
## Propose to fix autocomplete problems #327  

Still doesn't complete when the name is on quotes  
```sql
SELECT "asdf.a". -- no suggestion appears
```

### CODE REVIEW

**Comment by thiagola92** [comment]
There is too much ambiguity problem.

**Comment by rathboma** [comment]
Thanks for the PR! I'll take a look soon

**Comment by thiagola92** [comment]
I know that i commit to much so i will try to explain.  

Check if is a keyword before deciding if should quote or not.  
Try to split the schema to get the table/column names.  
If the table/column name need to be quote, quote it  
```javascript
        if (this.connectionType === 'postgresql')  {
          this.editor.on("beforeChange", (cm, co) => {
            const { to, from, origin, text } = co;

            const keywords = CodeMirror.resolveMode(this.editor.options.mode).keywords

            // quote names when needed
            if (origin === 'complete' && keywords[text[0].toLowerCase()] != true) {
              const names = text[0]
                .match(/("[^"]*"|[^.]+)/g)
                .map(n => /^\d/.test(n) ? `"${n}"` : n)
                .map(n => /[^a-z0-9_]/.test(n) && !/"/.test(n) ? `"${n}"` : n)
                .join('.')
  
              co.update(from, to, [names], origin)
            }
          })
        }
```

Removed wrapIdentifier

Quote columns names with dot, others columns that need quote will be quoted inside "beforeChange"  
Add quoted option for tables names  
If we accept table name with dot and without quote, we will never be able to discover the table/column name later
```javascript
hintOptions() {
        const result = {}
        this.tables.forEach(table => {
          const cleanColumns = table.columns.map(col => {
            return /\./.test(col.columnName) ? `"${col.columnName}"` : col.columnName
          })

          // add quoted option for everyone that needs to be quoted
          if (this.connectionType === 'postgresql' && (/[^a-z0-9_]/.test(table.name) || /^\d/.test(table.name)))
            result[`"${table.name}"`] = cleanColumns
          
          // don't add table names that can get in conflict with database schema 
          if (!/\./.test(table.name))
            result[table.name] = cleanColumns
        })
        return { tables: result }
      },
```

For curiosity, i notice that we check a lot if the conection type is postgresql, there is some reason for this? outside postgresql this operations are not allowed?

**Comment by rathboma** [comment]
Feels like our auto complete is getting more sophisticated, we should probably figure out a way to set up a test harness for this.

**Comment by rathboma** [comment]
I finally managed to review all this code. Looks awesome. Merging. Thanks for all the complex regex work. Feels like we're going to need a real SQL AST parser soon.

**Pull request merged**
