### PR TITLE
initial spreadsheet mode

### LINKED ISSUE #1507: FEAT: Excel-style range, column, and row selection for all tables
As a user I should be able to:

1. Select a column, or set of columns
2. Select a row, or set of rows
3. click and drag to select a range of cells

Then easily copy that selection, and paste into Excel.

Work on this has started in #1326

### PR DESCRIPTION
**Pull request by azmy60**
closes #1507 

work on selecting data on tables just like in google sheet!

image

image

Blocked on https://github.com/olifolkerd/tabulator/pull/4313

### CODE REVIEW

**Comment by rathboma** [comment]
@azmy60 looks like you'll need to merge master. I've seen you doing more work on the tabulator branch -- how close is this to being 'good enough' to merge?

**Comment by azmy60** [comment]
I found a list of small issues for spreadsheet in beekeeper. Most of them are styling so it should be very quick.

Also, one more fix from tabulator is that pressing context menu key from keyboard doesn't work. I'd finish all these most likely today. After that, we're good.

**Comment by azmy60** [comment]
After that, should I port my branch to our forked repo https://github.com/beekeeper-studio/tabulator ?  And change the package.json?

**Comment by azmy60** [comment]
Finally it's coming... :smiling_face_with_tear: :partying_face:

**Review by rathboma — APPROVED** [review]
If you're happy with where things are at performance-wise then merge away!

**Pull request merged**
