### PR TITLE
Table view column visibility toggle

### PR DESCRIPTION
**Pull request by fabscav**
This PR adds the ability to toggle column visibility on the table view via a popover, implementing the feature requested in #358.

When hiding one or more columns, the button triggering the popover changes its color to `info` in order to signify that not all available columns are being displayed.

FYI: While implementing this, I experienced a weird glitch that resulted in the column data not being reintroduced to the table when re-selecting a hidden column if the table data was re-rendered while that column was hidden, shifting the data and mismatching it to the headers. This issue seems to originate in tabulators virtual dom, since switching the `virtualDomHoz` option to the default `virtualDom` option fixed it. Is there any reason why `virtualDomHoz` was preferred to the default virtual dom method?

column_toggle

### CODE REVIEW

**Comment by rathboma** [comment]
Amazing PR! Thanks we'll review it soon.

One comment:

VirtualDomHoriz handles the virtual dom for horizontal scrolling. It's really important to keep that enabled. VirtualDom only handles up/down scrolling, and we paginate, so it doesn't really give us anything of much value. So please put back the virtualdomhoriz setting :-).

If you merge in Master we did upgrade tabulator to 4.8.2, so that bug might be fixed, if not -- can you raise an issue with oli on the Tabulator repo and explain the problem?

**Comment by fabscav** [comment]
I've created an issue on the Tabulator project since upgrading it to `4.8.2` did not solve the issue: olifolkerd/tabulator#3057

btw, it's mentioned in olifolkerd/tabulator#3055 that `virtualDomHoz` is an experimental feature meant for release in version `5.0` and is supposedly only beneficial when having 60+ columns.

**Comment by rathboma** [comment]
Yep! I've had several bug reports for folks with very wide database tables. Oli worked on `virtualDomHoriz` in part to help out this project.

Thanks, and let me know if anything comes of it

**Comment by olifolkerd** [comment]
Hey @rathboma 

As it is to help out my favourite Database Manager I will look at putting in a fix for this in the next release :)

Cheers

Oli :)

**Comment by rathboma** [comment]
Thanks @olifolkerd . You rock!

**Comment by olifolkerd** [comment]
I have just released version 4.8.4 which include a fix for this.

Happy Tabulating!

Oli :)

**Comment by fabscav** [comment]
Thank you so much @olifolkerd, you're awesome! I'll update this PR to include the new Tabulator version soon.

**Pull request merged**
