### PR TITLE
Copying single row resulting in object object fixed

### PR DESCRIPTION
**Pull request by therealrinku**
fixes: #1920

### CODE REVIEW

**Comment by azmy60** [comment]
@therealrinku This is great! Thanks for submitting the PR! :) Would you mind taking a look if this also happens with the other formats? (JSON/TSV/etc.)

**Comment by therealrinku** [comment]
Hey @azmy60 ! 
sure, I just checked and turns out there is same issue with TSV and Markdown as well.
I will push some changes for that too as soon as I can 😄

**Comment by therealrinku** [comment]
@azmy60 I was looking into fixing the same for tsv and markdown as well.
I'm thinking about maybe converting all the values from options.range.getData() to string before going to switch statement.

Let me know what do you think about that or if you have any other ideas on how to handle this better ?

**Comment by azmy60** [comment]
Yep. I think that sounds good! :)

**Review by azmy60 — APPROVED** [review]
@therealrinku This is awesome! Love the test! I also added a little change to your PR so we could prevent regression issues. :)

**Pull request merged**
