### PR TITLE
Add ability to add SSL certficate files

### PR DESCRIPTION
**Pull request by trevorrjohn**
This is the same as https://github.com/beekeeper-studio/beekeeper-studio/pull/109, I have just rebased the branch and made the necessary changes. 

Solves: https://github.com/beekeeper-studio/beekeeper-studio/issues/89

### CODE REVIEW

**Comment by trevorrjohn** [comment]
I have tested this with both a server that requires certificates and one that only requires SSL, both connections worked fine. However, I only tested with PostgreSQL (CloudSQL).

**Comment by rathboma** [comment]
Wow, thanks for adding this! I'll review over the weekend at make sure we're at least passing the correct files through to MySQL and SQL Server

**Review by rathboma — CHANGES_REQUESTED** [review]
First - these changes look fantastic. Thanks so much.

So the one remaining item is to add support for SqlServer. Could you do the same thing for the SQL Server driver?

The mssql node package uses 'tedius' as the Sql Server driver. Like PSQL and MySQL you can set the Ca file and such.

StackOverflow example: https://stackoverflow.com/questions/37987786/verify-certificate-from-sql-server-in-node

Docs: http://tediousjs.github.io/tedious/api-connection.html
Look for ` options.cryptoCredentialsDetails ` and ` options.trustServerCertificate `

**Comment by trevorrjohn** [comment]
@rathboma I have updated the PR. I was only able to go off the documentation you linked, so if you could test it with sql server that would be awesome.

**Comment by rathboma** [comment]
Looks great. One final thing -- I think you need to add the new cert fields to used_connection.ts and also copy them as part of the `copy` mechanism?

**Comment by trevorrjohn** [comment]
Good catch, there is one warning error I want to look at as well. Might be nothing.

**Comment by trevorrjohn** [comment]
@rathboma this should be good to go now.

**Comment by mholt** [comment]
Awesome! Does this work for CockroachDB as well?

Thanks so much for working on this.

**Comment by trevorrjohn** [comment]
@mholt my guess is it should, it uses the postgresql client. I cannot test it though. 

@rathboma I also added support for cassandradb.

**Comment by trevorrjohn** [comment]
@rathboma any chance you could put out a new release with  this? I have some non-technical co-workers that would love to start using this.

**Comment by rathboma** [comment]
@trevorrjohn Yes! I'll be putting together a release this week. I have quite a few things to test (thanks to lots of community contributions), including a major move to Typescript (!) for many components.

Stay tuned! It will be out soon :-D

**Pull request merged**
