### PR TITLE
Binary serialization

### PR DESCRIPTION
**Pull request by azmy60**
- Fix apply changes execution and sql string generation with binary or buffer values
- Implement serialization
- Show binary values correctly
- Auto "hex string to buffer" conversion in table view

https://github.com/user-attachments/assets/aab0411b-cc8e-49db-bb51-3646fe708ebc

### CODE REVIEW

**Comment by azmy60** [comment]
Yes. Clickhouse is prioritized as it seems that we only tested the latest version and not the older ones that folks are still using.

**Comment by azmy60** [comment]
Ok this is ready for review.

**Comment by azmy60** [comment]
This is how it works now:

Regardless of the column type, back-end will send UInt8Array to front-end if the the data is buffer.

The front-end will receive UInt8Array and keep that without mutating to string.

When applying changes, the front-end will send Uint8Array to back-end if the data's column is binary or the previous value in the same cell was a binary.

The data is sent as Uint8Array back and forth.

**Comment by rathboma** [comment]
@azmy60 broken test?

**Comment by azmy60** [comment]
@rathboma Just fixed it. Let me know what you think!

**Review by rathboma — APPROVED** [review]
Great stuff, ended up being a large PR

**Pull request merged**
