### PR TITLE
Change from codemirror to monaco editor

### PR DESCRIPTION
**Pull request by geovannimp**
Issue: https://github.com/beekeeper-studio/beekeeper-studio/issues/341

This is my WIP refactor to replace codemirror with monaco editor. Still a lot to do, but I'm already opening the PR to get early feedbacks and keep tracking my working.

Here are some TODOs to be completed. I'm accepting suggestions of course:

- [x] Change from code mirror to monaco
- [x] Add autocomplete to tables at select
- [x] Add autocomplete to columns at select
- [ ] Add autocomplete to tables at update
- [ ] Add autocomplete to columns at update
- [ ] Add autocomplete to tables at delete
- [ ] Add autocomplete to columns at delete
- [ ] Fix autocomplete code, cause it's working but is ugly
- [ ] Fix auto reload adding a new instance of autocomplete
- [ ] Check build size difference with the refactor

### CODE REVIEW

**Comment by rathboma** [comment]
Damn, this looks awesome! Let me poke around.

I know you have some good TODOs left over, but how do you think it compares with existing functionality? Are we close to parity?

**Comment by geovannimp** [comment]
@rathboma CodeMirror has some automatic autocomplete, so as we inform table and columns, just works out of the box.

With monaco editor we have to do it manually for every possible keyword: where, group by, join, etc...

For `SELECT foo FROM bar WHERE foo = anything` structure I think we have same functionality and maybe better. But I have to work with another keywords and update/delete.

**Comment by rathboma** [comment]
Gotcha.

The more you can add unit testing around your lib/ file, the easier this will be to test and refactor as we move it forward. I'm in favor of this editor change, and having auto-complete unit tests would be very very useful.

**Comment by geovannimp** [comment]
@rathboma I wrote the whole new TabQueryEditor component using the TS with class components. I did this to have autocomplete and be easy to refactor. But if you want we can change to classic vue style before merging.

**Comment by geovannimp** [comment]
> Gotcha.
> 
> The more you can add unit testing around your lib/ file, the easier this will be to test and refactor as we move it forward. I'm in favor of this editor change, and having auto-complete unit tests would be very very useful.

I liked the unit test idea and will be easier to implement autocomplete without having to reload beekeeper and rewrite the whole query again.

**Comment by rathboma** [comment]
I imagine this is a lot of work. Once we're done with the next release I should be able to jump in and help a little. If you can set up unit tests that would certainly make things a lot easier!

**Comment by geovannimp** [comment]
Unit tests working.  :)

**Comment by rathboma** [comment]
This still seems like a humongo amount of work, should I close the PR, or you still want to do this?

**Comment by geovannimp** [comment]
After rebase the branch stop working and I dont have time anymore to continue this work right now. You can close this PR.

If I fix those issues any time, I will open a new PR. :)

**Pull request closed without merging**
