### PR TITLE
Some quality of life improvements for autocomplete

### PR DESCRIPTION
**Pull request by mintsoft**
In my experience, the autocomplete of queries is the single most important feature of any DB querying tool; yet they're all terrible.

I've changed this as 2 small tweaks to always prefer user created tables first (users _very rarely_ are querying any of the builtins) and to fully qualify tables with their schema. 

image

Sort of heading towards fixing/improving https://github.com/beekeeper-studio/beekeeper-studio/issues/216

Happy to change tac or whatever as required; just let me know

### CODE REVIEW

**Comment by rathboma** [comment]
Nice! Let me take a look on Monday. Thanks for the PR :-)

**Comment by rathboma** [comment]
So I like the idea of auto-completing `schema.table`, a hack would be to add both of them to the table_hint results, what do you think?

I think in many cases folks don't bother writing `public`, so I don't want to force that.

**Comment by mintsoft** [comment]
Sure, I can try that @rathboma !

**Comment by mintsoft** [comment]
> So I like the idea of auto-completing schema.table, a hack would be to add both of them to the table_hint results, what do you think?

@rathboma actually I'm confused now I've had another look at the code, I think the above is what I've done?


> I think in many cases folks don't bother writing public, so I don't want to force that.
Good point! I've updated it so that for `public` it will now add it both with and without the schema so users can autocomplete both `public.blah` and `blah`.

**Comment by rathboma** [comment]
Nice. One last question -- for other DBs schema is usually `null`, so that probably needs a null check

**Pull request closed without merging**
