### PR TITLE
Add SSL CA, Cert and Key files

### PR DESCRIPTION
**Pull request by danilopolani**
Some notes:

1. I did not have tested this. On the paper it should work smoothly according to the docs, but I don't have any database with SSL enabled to use.
2. I copied the design of the `SSH` panel, I mean it was cool.
3. I don't know if it's better to have field like `full row, col col` or `full row, full row, full row` (see screenshots). I honestly prefer the `full row, col col` layout but up to you :)

Full row, col col
Full row, full row, full row

### CODE REVIEW

**Comment by rathboma** [comment]
wow, this is awesome! I'll try to get a database set up to test this with :-D

**Comment by rathboma** [comment]
Someone tested this and I don't think it works quite right, so I'll need to do some more in-depth testing, but to do that I'll need a 'real' database set up with real SSL certs.

**Comment by iketiunn** [comment]
Hi, since the binaries from Github Action is expired, I tested it using @danilopolani's source with my production GCP CloudSQL. And it works great.

OS: macOS 10.15.6
Source: https://github.com/danilopolani/beekeeper-studio/tree/feature/add-ssl-ca-file
Build: using  `yarn electron:serve`, remember to delete the outdated `yarn.lock`
Database: GCP CloudSQL: `PostgreSQL 12.3 on x86_64-pc-linux-gnu, compiled by Debian clang version 10.0.1 , 64-bit`

Screen Shot 2020-09-13 at 12 45 24 PM
Screen Shot 2020-09-13 at 12 46 25 PM

**Comment by rathboma** [comment]
@iketiunn does the production build work if you check the 'use ssl' box without providing a certificate?

**Comment by iketiunn** [comment]
> @iketiunn does the production build work if you check the 'use ssl' box without providing a certificate?

I test on the free postgres hosting: https://www.elephantsql.com/docs/faq.html#Does_ElephantSQL_support_TLS_SSL and it is fine.

Wondering what's the error message(with `pg` connector) showed up in https://github.com/beekeeper-studio/beekeeper-studio/issues/89#issuecomment-629380749 .

**Comment by mholt** [comment]
I would like to renew interest in this feature. How can I help?

**Comment by trevorrjohn** [comment]
> @iketiunn does the production build work if you check the 'use ssl' box without providing a certificate?

I have fixed this issue in https://github.com/beekeeper-studio/beekeeper-studio/pull/376

**Comment by trevorrjohn** [comment]
This can be closed now @rathboma

**Pull request closed without merging**
