### PR TITLE
Feature/747 find replace in editor

### PR DESCRIPTION
**Pull request by wmontgomery**
#747  
The styling presented is the default as given by codemirror with  an alteration to the length of the input field (inline style set it at 10em, I jumped it to 20em). I had considered having the label and input inline, but replace is written in a much different way that styling was becoming difficult to handle both sets, so decided to keep it the standard load out.

find-replace

find-light-theme

Update to button styles
image

### CODE REVIEW

**Comment by rathboma** [comment]
@wmontgomery can you add styling for the buttons they add in so they match our other buttons?

**Review by rathboma — CHANGES_REQUESTED** [review]
Lets try and apply our button styles here, make sure it works in both dark and light mode.

**Comment by wmontgomery** [comment]
@rathboma , Fix has been made. Issue getting the PR build for macos since it seems to want some kind of apple id/key to build stuff.

**Comment by rathboma** [comment]
Quick a before merging - does it look good in light mode also?

**Comment by wmontgomery** [comment]
Ah nuts, the dialog.scss file isn't bringing in the light variables as I expected it would, so the buttons are white when they should be black. I'll look into it.

**Comment by wmontgomery** [comment]
OK figured it out. Light theme update added

**Pull request merged**
