### PR TITLE
Fixes prompt's params when the query is selected

### PR DESCRIPTION
**Pull request by AJRDRGZ**
issue #1285

### CODE REVIEW

**Comment by AJRDRGZ** [comment]
Fix

**Comment by AJRDRGZ** [comment]
Sure, I can add it. @rathboma :+1:

**Comment by AJRDRGZ** [comment]
Hi @rathboma, sorry by the delay I was on a trip, I have included support for `run current query`. You can watch the result [here](https://www.loom.com/share/acb961d3daf04619bd96ef629b06da32).

**Comment by rathboma** [comment]
Thanks so much for this! It'll be in the next patch release

**Pull request merged**
