### PR TITLE
Dont show both menus, fixed wrong conditions

### LINKED ISSUE #262: BUG: There're two menu bars and two title bars after changing menu style to native
image

Beekeeper Version: 1.6.11
OS: Windows 10 1903

### PR DESCRIPTION
**Pull request by UtechtDustin**
This PR adjust the `v-if` condition for the titlebar to Fix #262

### CODE REVIEW

**Comment by UtechtDustin** [comment]
@rathboma your fix (https://github.com/beekeeper-studio/beekeeper-studio/commit/727702e1119c108757310e2257a30b28e2e5939e)
But then we also have to hide the `Menu style` menu item for `macos`.

**Comment by rathboma** [comment]
@UtechtDustin I think that should be hidden by the code in `Titlebar.vue`.

**Comment by rathboma** [comment]
This whole logic section is a total mess tbh

**Comment by rathboma** [comment]
Really App.vue should do two things:
1. Decide whether to display titlebar
2. Decide whether to display app menus

Then pass the second one into the titlebar class

`:displayAppMenu="displayAppMenu"`

But not super urgent so haven't done it

**Comment by UtechtDustin** [comment]
> @UtechtDustin I think that should be hidden by the code in `Titlebar.vue`.

Your right, didnt saw that one.
As you already wrote, its quite a mess right now :D

**Pull request closed without merging**
