### PR TITLE
Change openTable to only focus table when already opened

### PR DESCRIPTION
**Pull request by geovannimp**
Peek 04-09-2020 22-33

### CODE REVIEW

**Comment by UtechtDustin** [comment]
Does this make sense, what if you want multiple tabs with the same table for filtering multiple stuff ?
I understand that this makes sense for some of us, but i guess this should be a option not the default (or the other way around).

#197

**Comment by geovannimp** [comment]
If some filter has been made, it opens a new tab.
Peek 05-09-2020 04-21

**Comment by UtechtDustin** [comment]
Okay then it makes absolute sense!
I like it!

**Comment by geovannimp** [comment]
I made another PR to open the table with double click.
Maybe double click could focus if already opened and clicking at this button always open a new one.

**Comment by rathboma** [comment]
I've played with this before and decided not to add this behavior. I think in some ways it makes sense, but having multiple behaviors for the same button (focus vs open) based on an unknown context can be confusing.

I think I'd prefer not to do this and keep tab-opening actions fairly simple.

In the future I want to have a global-search which would allow you to jump to an open tab or open a new tab

**Pull request closed without merging**
