### PR TITLE
Show connection name in app title

### LINKED ISSUE #1052: FEAT: Connection info in Application title
I often have multiple connections to different DB servers open. I'm very happy to keep multiple windows open for each connection but as every window is titled "Beekeeper-Studio" it can be difficult to identify the window I'm looking for without squinting to see the connection colour at the bottom of the preview. 

image

If it could set the title to something like  "CONNECTION NAME - Beekeeper-Studio" it'd be far easier to identify the window I'm looking for.

### PR DESCRIPTION
**Pull request by azmy60**
Fixes #1052
Also mentioned in #1306

### CODE REVIEW

**Comment by rathboma** [comment]
Awesome, thanks!

**Comment by rathboma** [comment]
@azmy60 So I'm looking to hire someone for Beekeeper Studio development, either part time or full time. You've created some good PRs, would you be interested?

**Comment by azmy60** [comment]
@rathboma I'm very sorry. I already got a full time job (huge thanks to you for merging my PRs!), and I'm also doing a little side project with my brother. So I'm afraid I would not be able to handle it. But thanks for the offer!

**Comment by rathboma** [comment]
@azmy60 ok, if you end up not liking your job let me know - matthew at beekeeperstudio dot io

**Pull request merged**
