### PR TITLE
feat: make rows selectable

### PR DESCRIPTION
**Pull request by ad-on-is**
beekeeper-selectable

I implemented the selectable option for tabulator and added styling to the selected rows.

### CODE REVIEW

**Comment by azmy60** [comment]
#1083

**Comment by rathboma** [comment]
Awesome! We also have a pr #1170 which does similar things. I want to add a 'selector' on the left side of tables for selecting a row, like how Excel works, I worry about overloading the cell clicking with too many actions

**Comment by ad-on-is** [comment]
@rathboma  I just refactored it and added an empty cell for selecting. I also added a slight styling to make it look pleasing.
image

**Comment by Tubaleviao** [comment]
Fixes #904

**Comment by rathboma** [comment]
FYI I'm taking some of the work here and using it in Master in combination with #1310  to make tables much more selectable. Check it out:

row-selection

*coming soon (tm)

**Comment by rathboma** [comment]
Closing this in favor of #1326, although that is blocked by a feature that Tabulator needs.

**Pull request closed without merging**
