### PR TITLE
fix table name in sql copy

### LINKED ISSUE #1658: BUG: Wrong table name on "Copy Row (Insert)"
The copied text on "Copy Row (Insert)" after a query result is wrong. Insted of the table name the script begin with `insert into mytable`.

1. Write a select query without join
2. Right click on a row
3. Select "Copy Row (Insert)"
4. Paste the result

**Expected behavior**
The script begin with `insert into <query-table-name>` instead of `insert into mytable`

**Version Information:**
 - OS: Windows 10
 - App Version: 3.9.18
 - Database type and version: mySQL 5.7.18

### PR DESCRIPTION
**Pull request by azmy60**
fix #1658

Using `sql-query-identifier` from our fork repo => https://github.com/beekeeper-studio/sql-query-identifier/tree/table-identification-build

Beware that when Copying SQL from result table, the columns are still `c0`, `c1`, etc..

### CODE REVIEW

**Comment by rathboma** [comment]
@azmy60 Looks like you made changes to the sql-query-identifier library. Can you open a PR, or update the PR I already had?

**Comment by azmy60** [comment]
I couldn't update your PR so I made a new one. https://github.com/coresql/sql-query-identifier/pull/75

**Comment by rathboma** [comment]
Push to get sql-query-identifier changes merged, then update this to the new release and we're good

**Comment by rathboma** [comment]
Looks like changes were approved? Can we wrap this one up now?

**Comment by azmy60** [comment]
@rathboma Yes, I just updated the version.

**Review by rathboma — APPROVED** [review]
:tada: multiple libraries improved

**Pull request merged**
