### PR TITLE
add table limiter to tabletable

### LINKED ISSUE #941: FEAT: Configurable amount of rows returned per page. (currently seems to be 100 rows per page)
when using Beekeeper-studio with a large table, it appears to limit the number of returned rows to 100.

Would be excellent if there were a configuration that could be set for the number of returned rows per page.

### PR DESCRIPTION
**Pull request by azmy60**
Closes #941 

Animation4

### CODE REVIEW

**Comment by azmy60** [comment]
Not sure if having a button like this is great since we have a lot of things in status bar:

image

The other option is to have a modal that's solely for the limiter, but that feels a little bit too much? Having a button in status bar (or somewhere near the table) is more aligned with design patterns.

**Comment by rathboma** [comment]
@azmy60 can you add it to the :gear: menu? as a submenu?

**Comment by azmy60** [comment]
@rathboma like this?

image

I'm also thinking of adding a floating element at the bottom of screen like when you zoom in/out in chrome? so we can customize the limit numbers.

image

**Comment by rathboma** [comment]
What if we abandon this in favor of #1911. I like the idea of centralizing all the configuration in one place. We can also (eventually) add a settings screen

**Comment by rathboma** [comment]
Actually, yeah I really like the ini file.

**Comment by azmy60** [comment]
Yup that's a very nice idea.

**Comment by rathboma** [comment]
We can still allow users to change these settings in the app, but I think using an ini file as the core storage place is going to make that really flexible and nice to work with.

**Pull request closed without merging**
