### PR TITLE
add modal for importing sql files

### LINKED ISSUE #2042: BUG: Import saved queries tweaks (non urgent)
1. Add a `File -> Import .sql files` top level menu item
  - This should open a modal that says "This will make a **copy** of your .sql files and add them to your Beekeeper Studio saved queries. Any changes to the original .sql files will not be reflected in Beekeeper Studio", and has a `select files` box.
  - We want to make it clear that Beekeeper Studio is not going to track the .sql files when they are changed.
  - This needs to work in the client-side menu, and the electron-side menu

2. Fix the star icon in the dropdown menu for `import from workspace`
3. When clicking 'import .sql files' in the import dropdown, it should show the same modal as above.
Screenshot from 2024-03-24 14-11-20

### PR DESCRIPTION
**Pull request by azmy60**
fix #2042

### CODE REVIEW

**Comment by rathboma** [comment]
@azmy60 Can you add a little screen capture walkthrough to show how this works?

**Comment by azmy60** [comment]
https://github.com/beekeeper-studio/beekeeper-studio/assets/38707148/ed757225-d77c-4aba-b0ed-6de311a55737

Note: I also adjust the `FilePicker` so it can indicate that multiple files are attached.

**Review by rathboma — CHANGES_REQUESTED** [review]
This is great, please add this feature to the docs as part of the PR!

**Comment by azmy60** [comment]
@rathboma I just added a Saved Queries doc as a new page cause we don't have it yet, is that good?

**Comment by rathboma** [comment]
@azmy60 yes that's fine, but please replace your image placeholders with real images :-)

**Comment by azmy60** [comment]
Hmm, is it not showing? I've also submitted the images.


https://github.com/beekeeper-studio/beekeeper-studio/commit/b8fe862fc7c368c4c66fa3cff172d8eab8986a35

**Review by rathboma — APPROVED** [review]

**Pull request merged**
