### PR TITLE
#1572 - Fix for numeric schema names

### LINKED ISSUE #1572: Only schemas that show are now information_schema and pg_catalog
After updating to version 3.9.6, all of my schemas in a posgtresql database do not show in the left panel. Only `information_schema` and `pg_catalog` schemas show in the left panel.

**To Reproduce**
Create a new postgresql database, and create several schema in that database (I do mine via script in my application using localstack). Look in the left panel to see the schemas. They are not there.

**Expected behavior**
My schemas to be in the list and able to be inspected

**Screenshots / Gifs**
Screenshot

**Version Information (please complete the following information):**
 - OS: Mac
 - App Version 3.9.6
 - Database type and version Postgresql 13.3

### PR DESCRIPTION
**Pull request by not-night-but**
Fix #1572

### CODE REVIEW

**Comment by rathboma** [comment]
I think I shouldn't review yet as there's a test coming? Can you also test numeric names with tables and columns just to be sure?

**Comment by not-night-but** [comment]
@rathboma yeah sorry, I shoulda cancelled that request. Just finishing the test now, should be pushed in like 5 minutes.

**Comment by rathboma** [comment]
Lol omg this SQL with numbers. Nice work

**Review by rathboma — APPROVED** [review]

**Comment by davidkaufman** [comment]
From the "Just when you thought you knew enough about SQL" Department:

Adding this note for posterity: This dba.stackechange.com answer shows two generalized solutions to the vexxing problem of using (possibly bizarre, as we've seen) names of schemas and tables in joins like this, by either:

1. joining through, and on, on the `oid` values in the `pg_namespace` table, rather than trying to rely on the values in the names themselves.  It further complicates an already complicated join, but eliminates other similar risks, like spaces and "funny characters" in the names as well, or
3. if you have the "fully-qualified identifier", as we did in this example, using yet-another obscure pg-specific sql function: `parse_ident()`

from: https://dba.stackexchange.com/a/200172/272209:

## Solution 1: join on `pg_namespace.oid` instead of name

> > Can I just implement this function with e.g. `split_part(_tbl::text, '.', 1)`?
> 
> I'm not sure that would be safe. Instead, I would use,
> ~~~sql
> SELECT nspname
> FROM pg_catalog.pg_class AS c
> JOIN pg_catalog.pg_namespace AS ns
>   ON c.relnamespace = ns.oid
> WHERE c.oid = _tbl;
> ~~~
> That is guaranteed to work.
> 
> In writing a function to test if a column `col_name` exists in a table `_tbl`, I'd like to extract the table's schema name, which is passed into the function as a `regclass` parameter (for security??).
> 
> So you could do something like,
> ~~~sql
> SELECT nspname
> FROM pg_catalog.pg_attribute AS a
> JOIN pg_catalog.pg_class AS c
>   ON a.attrelid = c.oid
> JOIN pg_catalog.pg_namespace AS ns
>   ON c.relnamespace = ns.oid
> WHERE c.oid = _tbl
>   AND a.attname = col_name;
> ~~~
> 

## Solution 2: parse the identifier using `parse_ident()` function 🌟 

> ## Update
> 
> If you have a fully-qualified identifier, one with the table name, and schema name inside, You can use `parse_ident()`
> (https://dba.stackexchange.com/a/227419/2639) to parse it safely.

and, going just a bit deeper down that rabbit hole to https://dba.stackexchange.com/a/227419/272209:

> ~~~sql
> select parse_ident('abc,efi&xyz');
> ERROR:  string is not a valid identifier: "abc,efi&xyz"
> ~~~
> 
> They also do different things:
> 
> [parse_ident](https://www.postgresql.org/docs/current/functions-string.html) takes a string a fully-qualified identifier -- something you can use to identify a thing in a database, and returns the breakdown of it in an array. For example, if you had a column named `abc,efi&xyz` on a table named table in a schema named schema in a database named db, you could do,
> ~~~sql
> SELECT parse_ident('"abc,efi&xyz".table.schema.db');
>            parse_ident           
> ---------------------------------
>  {"abc,efi&xyz",table,schema,db}
> (1 row)
> ~~~
> From this point you could use array addressing to identify the table, `(parse_ident(...)[2])`.
> 
> regexp_split_to_array takes any string and simply splits it returning an array. Unlike parse_ident it doesn't require a fully-qualified identifier, and it doesn't understand ANSI-quotes inside the identifier (as I used in my example above).

That last is especially mind-blowingly cool 🤯  to me because I've never seen array-notation used in the SQL language!

**Comment by davidkaufman** [comment]
From the "Just when you thought you knew enough about SQL" Department:

Adding this note for posterity: This dba.stackechange.com answer shows two generalized solutions to the vexxing problem of using (possibly bizarre, as we've seen) names of schemas and tables in joins like this, by either:

1. joining through, and on, on the `oid` values in the `pg_namespace` table, rather than trying to rely on the values in the names themselves.  It further complicates an already complicated join, but eliminates other similar risks, like spaces and "funny characters" in the names as well, or
3. if you have the "fully-qualified identifier", as we did in this example, using yet-another obscure pg-specific sql function: `parse_ident()`

from: https://dba.stackexchange.com/a/200172/272209:

## Solution 1: join on `pg_namespace.oid` instead of name

> > Can I just implement this function with e.g. `split_part(_tbl::text, '.', 1)`?
> 
> I'm not sure that would be safe. Instead, I would use,
> ~~~sql
> SELECT nspname
> FROM pg_catalog.pg_class AS c
> JOIN pg_catalog.pg_namespace AS ns
>   ON c.relnamespace = ns.oid
> WHERE c.oid = _tbl;
> ~~~
> That is guaranteed to work.
> 
> In writing a function to test if a column `col_name` exists in a table `_tbl`, I'd like to extract the table's schema name, which is passed into the function as a `regclass` parameter (for security??).
> 
> So you could do something like,
> ~~~sql
> SELECT nspname
> FROM pg_catalog.pg_attribute AS a
> JOIN pg_catalog.pg_class AS c
>   ON a.attrelid = c.oid
> JOIN pg_catalog.pg_namespace AS ns
>   ON c.relnamespace = ns.oid
> WHERE c.oid = _tbl
>   AND a.attname = col_name;
> ~~~
> 

## Solution 2: parse the identifier using `parse_ident()` function 🌟 

> ## Update
> 
> If you have a fully-qualified identifier, one with the table name, and schema name inside, You can use `parse_ident()`
> (https://dba.stackexchange.com/a/227419/2639) to parse it safely.

and, going just a bit deeper down that rabbit hole to https://dba.stackexchange.com/a/227419/272209:

> ~~~sql
> select parse_ident('abc,efi&xyz');
> ERROR:  string is not a valid identifier: "abc,efi&xyz"
> ~~~
> 
> They also do different things:
> 
> [parse_ident](https://www.postgresql.org/docs/current/functions-string.html) takes a string a fully-qualified identifier -- something you can use to identify a thing in a database, and returns the breakdown of it in an array. For example, if you had a column named `abc,efi&xyz` on a table named table in a schema named schema in a database named db, you could do,
> ~~~sql
> SELECT parse_ident('"abc,efi&xyz".table.schema.db');
>            parse_ident           
> ---------------------------------
>  {"abc,efi&xyz",table,schema,db}
> (1 row)
> ~~~
> From this point you could use array addressing to identify the table, `(parse_ident(...)[2])`.
> 
> regexp_split_to_array takes any string and simply splits it returning an array. Unlike parse_ident it doesn't require a fully-qualified identifier, and it doesn't understand ANSI-quotes inside the identifier (as I used in my example above).

That last is especially mind-blowingly cool 🤯  to me because I've never seen array-notation used in the SQL language!

**Pull request merged**
