### PR TITLE
Feature/import scripts util process

### PR DESCRIPTION
**Pull request by wmontgomery**

### CODE REVIEW

**Review by rathboma — CHANGES_REQUESTED** [review]
I think you need to add signatures to `IBasicDatabaseClient`, and also implement the shims in `ElectronUtilityConnectionClient`

**Comment by rathboma** [comment]
After that, merge away!

**Comment by rathboma** [comment]
@wmontgomery fix the conflict then merge if the build is green

**Comment by wmontgomery** [comment]
Sure thing. Was a goal for tonight.

**Pull request merged**
