### PR TITLE
Feature/issue 1270 truncate table

### LINKED ISSUE #1270: FEAT: Add "Drop database" and "Drop table" on the context menu (right click) (and truncate, rename?)
**Is your feature request related to a problem? Please describe.**
I'm using an ORM during development that is migrating the database.
I need to DROP the table(s) or the database(s) some time to mage the migration pass.
A "Rename" and "Truncate" option would be great as well.

**Describe the solution you'd like**
You right click on the table/database name, a context menu appears with few options like "Drop" / "Rename" / "Refresh" /  "Truncate"

**Describe alternatives you've considered**
I'm using SQL query for now.

**Additional context**
image

**Database type, if appropriate**
All (I'm using it only for Postgresql till now).

### PR DESCRIPTION
**Pull request by wmontgomery**
This PR has both truncate and delete of tables and views.

fix #1270  part 2/2

### CODE REVIEW

**Comment by rathboma** [comment]
@wmontgomery I'll hold off reviewing this until the drop PR is updated and merged

**Comment by rathboma** [comment]
Blocked on #1322

**Comment by wmontgomery** [comment]
@rathboma PR is ready. I decided to keep the drop and truncate functions different first because I wanted them to be as single purpose as possible. Can always make it one function if you'd prefer. I'll admit I adhere to a "DRY enough" methodology.

**Comment by rathboma** [comment]
@wmontgomery can you merge master in to this branch? Then I'll review and (hopefully) merge on Monday

**Comment by wmontgomery** [comment]
@rathboma , master has been merged

**Pull request merged**
